# This is a comment
FROM example-scratch
MAINTAINER Paul Stuart <pauleyphonic@gmail.com>

#COPY shared/* /
ADD shared/dcman.tgz /

#ENTRYPOINT ["/dcman"]
#CMD ["-h"]
#CMD ["/dcman","-h"]
CMD ["/dcman"]

EXPOSE 8443

