# This is a comment
FROM alpine:latest
MAINTAINER Paul Stuart <pauleyphonic@gmail.com>

RUN apk update && apk upgrade
RUN apk add --update alpine-conf
RUN apk add --update ca-certificates && update-ca-certificates 
RUN apk add --update man man-pages mdocml-apropos
RUN apk add --update openrc-doc
RUN apk add --update openssl openssh 
RUN apk add --update bash curl python sqlite



